services:
  chatgpt-pyrogram-bot:
    image: ghcr.io/porcodio00033/chatgpt-pyrogram-bot:nightly
    container_name: chatgpt_pyrogram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Persist data (logs, etc.)
      - ${HOST_PERSISTENT_PATH}/data:/app/data
