[project]
name = "chatgpt-pyrogram-bot"
version = "0.1.0"
description = "fork of https://github.com/MarshalX/chatgpt-telegram-bot migrated from PTB to pyrogram plus other changes"
authors = [
    {name = "m4t7w@github"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "python-dotenv (==1.2.1)",
    "pydub (==0.25.1)",
    "tiktoken (==0.12.0)",
    "openai (==2.8.1)",
    "tenacity (==8.5.0)",
    "wolframalpha (>=5.0.0,<5.1.0)",
    "ddgs (==9.9.0)",
    "spotipy (>=2.25.1,<2.26.0)",
    "pytube (>=15.0.0,<15.1.0)",
    "gtts (>=2.5.1,<2.6.0)",
    "whois (>=0.9.27,<0.10.0)",
    "pillow (>=12.0.0,<12.1.0)",
    "httpx (==0.28.1)",
    "readability-lxml (==0.8.4.1)",
    "lxml-html-clean (==0.4.2)",
    "youtube-transcript-api (==1.2.3)",
    "asyncpg (==0.30.0)",
    "google-api-python-client (==2.140.0)",
    "pypdf (==6.4.0)",
    "aiofiles (==25.1.0)",
    "tzdata (>=2025.2,<2026.0)",
    "pyrotgfork (>=2.2.16,<3.0.0)",
    "pytgcrypto @ git+https://github.com/TelegramPlayground/pyrogram-tgcrypto.git@v1.2.11",
    "pysocks (>=1.7.1,<2.0.0)",
    "pyaes (>=1.6.1,<2.0.0)",
    "uvloop (==0.22.1) ; sys_platform not in 'win32 cygwin cli'",
    "winloop (==0.4.0) ; sys_platform in 'win32 cygwin cli'",
    "audioop-lts (==0.2.2) ; python_version >= \"3.13\"",
    "lottie[video] (>=0.7.2,<0.8.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "watchdog (==4.0.0)",
    "ruff (==0.14.5)"
]
